// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKhrHgg8cMT6ZeawpFDrliO27UhyHqD5Y',
    appId: '1:908582132976:web:b26b68c8d92d3e3093f635',
    messagingSenderId: '908582132976',
    projectId: 'praticalproject-57474',
    authDomain: 'praticalproject-57474.firebaseapp.com',
    databaseURL: 'https://praticalproject-57474-default-rtdb.firebaseio.com',
    storageBucket: 'praticalproject-57474.appspot.com',
    measurementId: 'G-PVKC28357R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDuQAV1x6G0XcUL1dphikSSYiDU9e58Uk',
    appId: '1:908582132976:android:e9ee51a4b6e35e4d93f635',
    messagingSenderId: '908582132976',
    projectId: 'praticalproject-57474',
    databaseURL: 'https://praticalproject-57474-default-rtdb.firebaseio.com',
    storageBucket: 'praticalproject-57474.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLgto09SJQHP4e_be68ej7Yp2sAVmGjI',
    appId: '1:908582132976:ios:c8342e0f64c3571593f635',
    messagingSenderId: '908582132976',
    projectId: 'praticalproject-57474',
    databaseURL: 'https://praticalproject-57474-default-rtdb.firebaseio.com',
    storageBucket: 'praticalproject-57474.appspot.com',
    iosClientId: '908582132976-atrpbusso505h1jm0lq68845b44e6i1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLgto09SJQHP4e_be68ej7Yp2sAVmGjI',
    appId: '1:908582132976:ios:c8342e0f64c3571593f635',
    messagingSenderId: '908582132976',
    projectId: 'praticalproject-57474',
    databaseURL: 'https://praticalproject-57474-default-rtdb.firebaseio.com',
    storageBucket: 'praticalproject-57474.appspot.com',
    iosClientId: '908582132976-atrpbusso505h1jm0lq68845b44e6i1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKhrHgg8cMT6ZeawpFDrliO27UhyHqD5Y',
    appId: '1:908582132976:web:631899b7ea9798da93f635',
    messagingSenderId: '908582132976',
    projectId: 'praticalproject-57474',
    authDomain: 'praticalproject-57474.firebaseapp.com',
    databaseURL: 'https://praticalproject-57474-default-rtdb.firebaseio.com',
    storageBucket: 'praticalproject-57474.appspot.com',
    measurementId: 'G-6QMFM7ZETB',
  );

}